export const USING_MOCKUP = true;
export const BACKEND_URL = '';

export const STATUS_MSG_100_YET_TO_SENT = 'STATUS (100): REQUEST IS YET TO BE SENT.';

export const ERROR_MSG_404 = 'ERROR (404): RESOURCE NOT FOUND.';
export const ERROR_MSG_400 = 'ERROR (400): BAD REQUEST.';
export const ERROR_MSG_400_NOT_AN_ASSET = 'ERROR (400): BAD REQUEST. THE RESOURCE IS NOT AN ASSET.';
export const ERROR_MSG_400_NOT_IMPLEMENTED = 'ERROR (400): BAD REQUEST. THIS FEATURE SHOULD NOT BE IMPLEMENTED IN THIS VERSION.';
export const ERROR_MSG_400_INVALID_PATH = 'ERROR (400): BAD REQUEST. THE RESOURCE PATH IS NOT VALID.';
